/*
Problem: 389. Find the Difference

Description: You are given two strings s and t. String t is generated by random shuffling string s and then add one
more letter at a random position. Return the letter that was added to t.

Constraints:
- 0 <= s.length <= 1000
- t.length == s.length + 1
- s and t consist of lowercase English letters.

 */

import java.util.ArrayList;
import java.util.Collections;

public class FindTheDifference {
    /*
        LeetCode Stats:
        - Runtime: 13ms (Beats 6.35% of users with Java)
        - Memory: 41.83MB (Beats 5.28% of users with Java)
     */
    public char findTheDifference(String s, String t) {
        ArrayList<Character> sArray = new ArrayList<>();
        ArrayList<Character> tArray = new ArrayList<>();
        for(char letter : s.toCharArray()) sArray.add(letter);
        for(char letter : t.toCharArray()) tArray.add(letter);
        Collections.sort(sArray);
        Collections.sort(tArray);

        for(int i=0; i<t.length(); i++) {
            if(i == t.length()-1) return tArray.get(i); // last letter
            if(sArray.get(i) != tArray.get(i)) return tArray.get(i);
        }

        return 0;
    }
}
